version: "3.7"

services:
  postgres: &postgres
    build: .
    restart: always
    env_file: .env
    volumes:
      - /var/lib/postgresql/data
    profiles: ["_ignored"]

  postgres-master:
    <<: *postgres
    profiles: []
    ports:
      - "5432:5432"
    # environment:
    #   - REPLICATE_FROM=pg-slave #only after pg-slave get promoted

  # #Promote to master `select pg_promote(true,60);`
  postgres-slave:
    <<: *postgres
    profiles: []
    ports:
      - "2432:5432"
    environment:
      - REPLICATE_FROM=postgres-master
    depends_on:
      - "postgres-master"
