version: "3.7"

services:
  postgres-master: &postgres
    build: .
    image: arm32v7/postgres:14-replica
    hostname: postgres-master
    restart: always
    env_file: .env
    volumes:
      - /var/lib/postgresql/data
    ports:
      - "5432:5432"

  # #Promote to master `select pg_promote(true,60);`
  postgres-slave:
    <<: *postgres
    hostname: postgres-slave-{{.Task.Slot}}
    ports:
      - "2432:5432"
    environment:
      - REPLICATE_FROM=postgres-master
    depends_on:
      - "postgres-master"
