version: "3.7"

x-postgres: &postgres
  build: .
  image: arm32v7/postgres:14-replica
  hostname: postgres-master
  restart: always
  env_file: ${PWD}/postgres.env

services:
  postgres-master:
    <<: *postgres
    hostname: postgres-master

  # #Promote to master `select pg_promote(true,60);`
  postgres-slave:
    <<: *postgres
    hostname: postgres-slave-{{.Task.Slot}}
    # This will only work if it's replicated only once to the same host
    # If you want to replicate more than 1, see:
    #   - https://github.com/moby/moby/issues/26445#issuecomment-246074751
    #   - https://stackoverflow.com/a/64298786
    #   - https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates
    #   - https://docs.docker.com/engine/reference/commandline/config_create/
    environment:
      - REPLICATE_FROM=postgres-master
    depends_on:
      - "postgres-master"
