version: "3.7"

volumes:
  postgres-master:
    external: true
  postgres-slave:
    external: true

services:
  postgres-master: &postgres
    build: .
    image: arm32v7/postgres:14-replica
    hostname: postgres-master
    restart: always
    env_file: .env
    volumes:
      - postgres-master:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # #Promote to master `select pg_promote(true,60);`
  postgres-slave:
    <<: *postgres
    hostname: postgres-slave-{{.Task.Slot}}
    # This will only work if it's replicated only once to the same host
    # If you want to replicate more than 1, see:
    #   - https://github.com/moby/moby/issues/26445#issuecomment-246074751
    #   - https://stackoverflow.com/a/64298786
    #   - https://docs.docker.com/engine/reference/commandline/service_create/#create-services-using-templates
    #   - https://docs.docker.com/engine/reference/commandline/config_create/
    volumes:
      - postgres-slave:/var/lib/postgresql/data
    ports:
      - "2432:5432"
    environment:
      - REPLICATE_FROM=postgres-master
    depends_on:
      - "postgres-master"
